name: Gerar APK Android

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extrair o Código
      uses: actions/checkout@v4

    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permissão ao compilador
      run: chmod +x gradlew

    - name: Compilar o Aplicativo
      run: ./gradlew assembleDebug

    - name: Salvar o APK pronto
      uses: actions/upload-artifact@v4
      with:
        name: Scanner-EMF-Instalador
        path: app/build/outputs/apk/debug/app-debug.apk
        
